parameters:
#    canal_tp_mtt_business_app.example.class: CanalTP\MttBusinessAppBundle\Example

services:
#    canal_tp_mtt_business_app.example:
#        class: %canal_tp_mtt_business_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
