parameters:
    sam.business_component.mtt.class: CanalTP\MttBridgeBundle\Security\BusinessComponent
    sam.business_module.mtt.class: CanalTP\MttBridgeBundle\Security\BusinessModule
    sam.business_permission_manager.mtt.class: CanalTP\MttBridgeBundle\Security\BusinessPermissionManager
    sam.business_perimeter_manager.mtt.class: CanalTP\MttBridgeBundle\Security\BusinessPerimeterManager
    # Monitoring
    sam.business_monitoring.mtt.class: CanalTP\MttBridgeBundle\Monitoring\Component

services:
    sam.business_module.mtt:
        class: "%sam.business_module.mtt.class%"
        arguments: ['%mtt.permissions%']
        public: false

    sam.business_permission_manager.mtt:
        class: "%sam.business_permission_manager.mtt.class%"
        arguments: ['@sam.business_module.mtt']
        public: false

    sam.business_perimeter_manager.mtt:
        class: "%sam.business_perimeter_manager.mtt.class%"
        arguments: ['@canal_tp_mtt.network_manager']
        public: false

    sam.business_component.mtt:
        class: "%sam.business_component.mtt.class%"
        arguments: ['@sam.business_permission_manager.mtt', '@sam.business_perimeter_manager.mtt', '@canal_tp_mtt.user']
        public: false

    # Monitoring
    sam.business_monitoring.mtt:
        class: "%sam.business_monitoring.mtt.class%"

    mtt.service_monitoring.database.pgsql:
        class: "%sam.service_monitoring.database.pgsql.class%"
        arguments: [%database_host%, %database_port%, %database_name%, %database_user%, %database_password%]
        tags:
            - { name: service_monitoring, category: Tech }

    mtt.service_monitoring.supervisord:
        class: "%sam.service_monitoring.http.rest.class%"
        arguments: [%monitoring.sam.supervisord.url%, 'Supervisord']
        tags:
            - { name: service_monitoring, category: Tech }

    mtt.service_monitoring.pdf_generator:
        class: "%sam.service_monitoring.http.rest.class%"
        arguments: [%monitoring.sam.pdf_generator.url%, 'Pdf Generator']
        tags:
            - { name: service_monitoring, category: Tech }

    mtt.service_monitoring.login:
        class: "%sam.service_monitoring.http.rest.class%"
        arguments: [%monitoring.sam.host%, 'TimeTable Application', 302]
        tags:
            - { name: service_monitoring, category: Business }

    mtt.service_monitoring.rabbit_mq:
        class: "%sam.service_monitoring.message_broker.rabbit_mq.class%"
        arguments: [%canal_tp_mtt.amqp_server_host%, %canal_tp_mtt.amqp_server_port%, %canal_tp_mtt.amqp_server_vhost%, %canal_tp_mtt.amqp_server_user%, %canal_tp_mtt.amqp_server_pass%]
        tags:
            - { name: service_monitoring, category: Tech }

    mtt.service_monitoring.media_manager:
        class: "%sam.service_monitoring.media_manager.class%"
        arguments: [%monitoring.mtt.media_manager.path%]
        tags:
            - { name: service_monitoring, category: Tech }
