parameters:
    sam.business_component.mtt.class: CanalTP\MttBridgeBundle\Security\BusinessComponent
    sam.business_module.mtt.class: CanalTP\MttBridgeBundle\Security\BusinessModule
    sam.business_permission_manager.mtt.class: CanalTP\MttBridgeBundle\Security\BusinessPermissionManager
    sam.business_perimeter_manager.mtt.class: CanalTP\MttBridgeBundle\Security\BusinessPerimeterManager
    # Monitoring
    sam.business_monitoring.mtt.class: CanalTP\MttBridgeBundle\Monitoring\Component

services:
    sam.business_module.mtt:
        class: "%sam.business_module.mtt.class%"
        arguments: ['%mtt.permissions%']
        public: false

    sam.business_permission_manager.mtt:
        class: "%sam.business_permission_manager.mtt.class%"
        arguments: ['@sam.business_module.mtt']
        public: false

    sam.business_perimeter_manager.mtt:
        class: "%sam.business_perimeter_manager.mtt.class%"
        arguments: ['@canal_tp_mtt.network_manager']
        public: false

    sam.business_component.mtt:
        class: "%sam.business_component.mtt.class%"
        arguments: ['@sam.business_permission_manager.mtt', '@sam.business_perimeter_manager.mtt', '@canal_tp_mtt.user']
        public: false

    # Monitoring
    sam.business_monitoring.mtt:
        class: "%sam.business_monitoring.mtt.class%"

    mtt.service_monitoring.database.psql:
        class: "%sam.service_monitoring.database.psql.class%"
        arguments: [%database_host%, %database_port%, %database_name%, %database_user%, %database_password%]
        tags:
            - { name: service_monitoring, category: Tech }
            
    mtt.service_monitoring.ws:
        class: "%sam.service_monitoring.rest.class%"
        arguments: ['http://samback/app_dev.php/mtt/urlduwebservice', 'ws']
        tags:
            - { name: service_monitoring, category: Tech }
            
    mtt.service_monitoring.login:
        class: "%sam.service_monitoring.rest.class%"
        arguments: ['http://samback/app_dev.php/admin/login', 'login']
        tags:
            - { name: service_monitoring, category: Business }
